Repository GSG-G8/p2p-money, pull requests merged in 2020-07, with the labels that each got.

#103 Front End || Sider Client Component
  client/package-lock.json
  client/src/components/App/index.js
  client/src/components/client/sider/index.js
  client/src/components/client/sider/style.css
Labels: Done, FrontEnd, React, React component, client

#129 Edits in App
  client/src/components/App/index.js
  client/src/components/pages/common/Home/index.js
  client/src/components/pages/common/Login/index.js
  package.json
Labels: Done, React

#131 Fixed login backend error
  server/controllers/auth/login.js
Labels: Backend, Done, Express, bug

#126 create header component
  client/public/index.html
  client/src/assets/icons/headerIcon.svg
  client/src/components/Common/Button/index.js
  client/src/components/Common/Button/style.css
  client/src/components/Common/Header/index.js
  client/src/components/Common/Header/style.css
Labels: Done

#120 admin component chart
  client/package-lock.json
  client/package.json
  client/public/index.html
  client/public/p2p.ico
  client/public/p2p.svg
  client/src/components/App/index.js
  client/src/components/admin/Chart/index.js
  client/src/components/admin/Chart/queryReport.js
  client/src/components/admin/Chart/style.css
Labels: Done, FrontEnd, admin, design

#132 Client Side | Front-end Route: Wallet
  client/src/components/client/sider/index.js
  client/src/components/client/sider/style.css
  client/src/components/pages/client/Wallet/index.js
  client/src/components/pages/client/Wallet/style.css
Labels: Done, FrontEnd, React, client

#127 create transaction route
  server/controllers/auth/signup.js
  server/controllers/routes/client/createTransaction.js
  server/controllers/routes/client/index.js
  server/database/data/client.js
  server/database/models/client.js
  server/database/models/prices.js
  server/router/transaction.js
  server/utils/validations/createTransactionValidation.js
Labels: Done

#135 fixed wallet page
  client/src/components/pages/client/Wallet/index.js
  client/src/components/pages/client/Wallet/style.css
Labels: React, client, enhancement

#128 SignUp Page Common Page
  .gitignore
  client/.env
  client/.gitignore
  client/package-lock.json
  client/package.json
  client/src/assets/images/.gitignore
  client/src/assets/images/signUpImg.svg
  client/src/components/App/index.js
  client/src/components/Common/Alert/index.js
  client/src/components/Common/Typography/index.js
  client/src/components/pages/client/Signup/AntFormatConfigurations.js
  client/src/components/pages/client/Signup/firebase.js
  client/src/components/pages/client/Signup/index.js
  client/src/components/pages/client/Signup/signUpForm.js
  client/src/components/pages/client/Signup/style.css
  client/src/style.css
  server/controllers/auth/signup.js
Labels: Done, FrontEnd Routes

#136 fixed wallet table styling
  client/src/components/pages/client/Wallet/style.css
Labels: Done, React, bug

#134 27 login page
  client/src/components/Common/Typography/index.js
  client/src/components/pages/client/Signup/AntFormatConfigurations.js
  client/src/components/pages/client/Signup/signUpForm.js
  client/src/components/pages/common/Login/LoginForm.js
  client/src/components/pages/common/Login/index.js
  client/src/components/pages/common/Login/style.css
Labels: Done

#133 Banks Front Route [Client]
  client/src/components/App/index.js
  client/src/components/Common/TextInput/index.js
  client/src/components/Common/selectBox/index.js
  client/src/components/Common/selectBox/style.css
  client/src/components/client/sider/index.js
  client/src/components/pages/client/Bank/arabicCurrency.js
  client/src/components/pages/client/Bank/index.js
  client/src/components/pages/client/Bank/style.css
  server/controllers/routes/client/addNewBank.js
  server/controllers/routes/client/deleteBankAccount.js
  server/router/client.js
  server/utils/validations/addBankValidation.js
Labels: Done, FrontEnd Routes

#138 Home front end route
  client/src/assets/icons/bankPrice.svg
  client/src/assets/icons/ourPrice.svg
  client/src/assets/icons/tellerPrice.svg
  client/src/assets/images/HomeMap.svg
  client/src/assets/images/background.svg
  client/src/components/App/index.js
  client/src/components/Common/Footer/index.js
  client/src/components/Common/Footer/style.css
  client/src/components/Common/Header/index.js
  client/src/components/Common/Header/style.css
  client/src/components/Common/TextInput/index.js
  client/src/components/Common/TextInput/style.css
  client/src/components/Common/selectCurrency/index.js
  client/src/components/client/mainCardCurrencies/index.js
  client/src/components/client/mainCardCurrencies/style.css
  client/src/components/client/sider/style.css
  client/src/components/pages/client/Signup/signUpForm.js
  client/src/components/pages/client/Wallet/index.js
  client/src/components/pages/client/Wallet/style.css
  client/src/components/pages/common/Home/index.js
  client/src/components/pages/common/Home/style.css
  server/controllers/routes/client/createTransaction.js
  server/database/data/prices.js
Labels: FrontEnd, FrontEnd Routes, React, awaiting review

#137 change site logo
  client/public/index.html
  client/public/p2p.svg
  client/src/assets/icons/cardIcon.svg
  client/src/assets/icons/footerIcon.svg
  client/src/assets/icons/headerIcon.svg
  client/src/assets/icons/homeIcon.svg
  client/src/assets/icons/icon.svg
  client/src/assets/images/signUpImg.svg
  client/src/components/Common/Footer/index.js
  client/src/components/Common/Footer/style.css
  client/src/components/Common/Header/index.js
  client/src/components/Common/Header/style.css
  client/src/components/client/mainCardCurrencies/style.css
  client/src/components/client/sider/index.js
  client/src/components/client/sider/style.css
  client/src/components/pages/client/Signup/signUpForm.js
  client/src/components/pages/common/Home/index.js
  client/src/components/pages/common/Home/style.css
  client/src/components/pages/common/Login/LoginForm.js
Labels: Done

#140 Dashboard Admin Page Layout
  client/src/components/admin/AdminCard/index.js
  client/src/components/admin/AdminCard/style.css
  client/src/components/admin/Chart/index.js
  client/src/components/admin/Chart/style.css
  client/src/components/admin/clientsCard/index.js
  client/src/components/pages/admin/dashboard/index.js
  client/src/components/pages/admin/dashboard/style.css
Labels: Done

#141 changed select component
  client/src/assets/icons/arrow.svg
  client/src/components/Common/Header/index.js
  client/src/components/Common/selectCurrency/index.js
  client/src/components/Common/selectCurrency/style.css
  client/src/components/client/mainCardCurrencies/index.js
  client/src/components/client/mainCardCurrencies/style.css
  client/src/components/pages/common/Home/index.js
  client/src/components/pages/common/Home/style.css
Labels: Done, FrontEnd, React, React component

#146 change text in Home
  client/src/components/pages/common/Home/index.js
Labels: Done

#145 create loading component and update 404 page
  client/src/components/App/index.js
  client/src/components/Common/Loading/index.js
  client/src/components/Common/Loading/style.css
  client/src/components/pages/client/Signup/signUpForm.js
  client/src/components/pages/common/Error404/index.js
  client/src/components/pages/common/Error404/style.css
  client/src/components/pages/common/Login/LoginForm.js
Labels: Done

#139 Client Side | Front-end Route: Settings
  client/package-lock.json
  client/src/components/App/index.js
  client/src/components/Common/TextInput/index.js
  client/src/components/Common/TextInput/style.css
  client/src/components/Common/selectBox/index.js
  client/src/components/Common/selectBox/style.css
  client/src/components/client/sider/index.js
  client/src/components/client/sider/style.css
  client/src/components/pages/client/Setting/AvatarPop.js
  client/src/components/pages/client/Setting/index.js
  client/src/components/pages/client/Setting/style.css
  client/src/components/pages/client/Wallet/index.js
  server/controllers/routes/client/updateClient.js
Labels: Done, React, client

#148 Fixed some problems
  client/src/components/Common/selectBox/AdminSelect.js
  client/src/components/admin/Chart/index.js
  client/src/components/admin/Chart/queryReport.js
  client/src/components/admin/Chart/style.css
  client/src/components/pages/admin/dashboard/style.css
  client/src/components/pages/client/Bank/index.js
  client/src/components/pages/client/Bank/style.css
  client/src/components/pages/client/Signup/firebase.js
  client/src/components/pages/client/Signup/signUpForm.js
  client/src/components/pages/common/Home/index.js
  client/src/components/pages/common/Login/LoginForm.js
Labels: Done, FrontEnd, React, React component

#143 Update Prices [Admin Dashboard]
  client/src/components/Common/Alert/index.js
  client/src/components/Common/TextInput/index.js
  client/src/components/admin/AdminCard/index.js
  client/src/components/admin/clientsCard/index.js
  client/src/components/pages/admin/dashboard/index.js
  client/src/components/pages/admin/dashboard/style.css
  client/src/components/pages/admin/dashboard/updatePrice.js
  client/src/components/pages/client/Bank/index.js
  client/src/components/pages/client/Setting/style.css
  server/controllers/routes/prices/updatePrices.js
Labels: Done
